import { OutputSuccess } from '../transform/types'
import elasticCodeGen, { ElasticInputType } from './elastic'
import { name, typeDef } from './common'

export const server = (contracts: OutputSuccess[]): string => {
  const valueDef = contracts.map(x => {
    let handle = 'undefined'
    if (x.preferredImplementation && x.preferredImplementation.type === 'elasticsearch') {
      const elin:ElasticInputType = x.method === 'get'
        ? { method: x.method, search: x.search || 'idOnly' }
        : { method: x.method }

      handle = elasticCodeGen(x.preferredImplementation, elin)
    }

    return `${name(x)}: {
          name: "${x.name}",
          authentication: ${JSON.stringify(x.authentication, undefined, 2)},
          type: "${x.method}",
          handle: ${handle},
          arguments: ${JSON.stringify(x.arguments)} ,
          returns: ${JSON.stringify(x.returns)}}`
  }).join(',\n')

  const contractTypeList = contracts.map(x =>
    `${name(x)}: ContractType<${name(x)}Argument, ${name(x)}Returns>`).join('\n')

  const elastic = contracts.find(x => x.preferredImplementation?.type === 'elasticsearch')

  const elasticImport = elastic ? ', elastic' : ''

  const result =
  `/**********************************************
   DO NOT EDIT THIS FILE, IT WILL BE OVERRIDDEN
***********************************************/
  import { ContractType${elasticImport} } from "declarapi"

  ${typeDef(contracts)}
  export type ContractListType = {\n${contractTypeList}\n}\n
  export const contracts: ContractListType = {\n${valueDef}\n}\n`

  return result
}

export default server
