/**********************************************
   DO NOT EDIT THIS FILE, IT WILL BE OVERRIDDEN
***********************************************/
  import { ContractType, elastic } from "declarapi"

  /** elasticsearchSearchExample types for get method **/
export type elasticsearchSearchExampleGetArgument = { search?: string | undefined; id?: string | string[] | undefined } | undefined
export type elasticsearchSearchExampleGetReturns = ({ id: string; name: string; ownerId: string; dogs: ({ name: string; color: string; age: number; breed: "Labrador Retriever" | "German Shepherd Dog" | "Golden Retriever" | "French Bulldog" | "Bulldog" })[]; cats: ({ name: string; color: string; age: number; breed: "Siamese" | "Persian" | "Maine Coon" | "Ragdoll" | "Bengal" })[]; rain: "cats" | "dogs" })[]

/** elasticsearchSearchExample types for post method **/
export type elasticsearchSearchExamplePostArgument = { id?: string | undefined; name: string; ownerId: string; dogs: ({ name: string; color: string; age: number; breed: "Labrador Retriever" | "German Shepherd Dog" | "Golden Retriever" | "French Bulldog" | "Bulldog" })[]; cats: ({ name: string; color: string; age: number; breed: "Siamese" | "Persian" | "Maine Coon" | "Ragdoll" | "Bengal" })[]; rain: "cats" | "dogs" }
export type elasticsearchSearchExamplePostReturns = { id: string; name: string; ownerId: string; dogs: ({ name: string; color: string; age: number; breed: "Labrador Retriever" | "German Shepherd Dog" | "Golden Retriever" | "French Bulldog" | "Bulldog" })[]; cats: ({ name: string; color: string; age: number; breed: "Siamese" | "Persian" | "Maine Coon" | "Ragdoll" | "Bengal" })[]; rain: "cats" | "dogs" }

/** elasticsearchSearchExample types for put method **/
export type elasticsearchSearchExamplePutArgument = { id: string; name: string; ownerId: string; dogs: ({ name: string; color: string; age: number; breed: "Labrador Retriever" | "German Shepherd Dog" | "Golden Retriever" | "French Bulldog" | "Bulldog" })[]; cats: ({ name: string; color: string; age: number; breed: "Siamese" | "Persian" | "Maine Coon" | "Ragdoll" | "Bengal" })[]; rain: "cats" | "dogs" }
export type elasticsearchSearchExamplePutReturns = { id: string; name: string; ownerId: string; dogs: ({ name: string; color: string; age: number; breed: "Labrador Retriever" | "German Shepherd Dog" | "Golden Retriever" | "French Bulldog" | "Bulldog" })[]; cats: ({ name: string; color: string; age: number; breed: "Siamese" | "Persian" | "Maine Coon" | "Ragdoll" | "Bengal" })[]; rain: "cats" | "dogs" }

/** elasticsearchSearchExample types for patch method **/
export type elasticsearchSearchExamplePatchArgument = { id: string; name?: string | undefined; ownerId?: string | undefined; dogs?: ({ name: string; color: string; age: number; breed: "Labrador Retriever" | "German Shepherd Dog" | "Golden Retriever" | "French Bulldog" | "Bulldog" })[] | undefined; cats?: ({ name: string; color: string; age: number; breed: "Siamese" | "Persian" | "Maine Coon" | "Ragdoll" | "Bengal" })[] | undefined; rain?: "cats" | "dogs" | undefined }
export type elasticsearchSearchExamplePatchReturns = { id: string; name: string; ownerId: string; dogs: ({ name: string; color: string; age: number; breed: "Labrador Retriever" | "German Shepherd Dog" | "Golden Retriever" | "French Bulldog" | "Bulldog" })[]; cats: ({ name: string; color: string; age: number; breed: "Siamese" | "Persian" | "Maine Coon" | "Ragdoll" | "Bengal" })[]; rain: "cats" | "dogs" }

/** elasticsearchSearchExample types for delete method **/
export type elasticsearchSearchExampleDeleteArgument = { id: string | string[] }
export type elasticsearchSearchExampleDeleteReturns = ({ id: string; name: string; ownerId: string; dogs: ({ name: string; color: string; age: number; breed: "Labrador Retriever" | "German Shepherd Dog" | "Golden Retriever" | "French Bulldog" | "Bulldog" })[]; cats: ({ name: string; color: string; age: number; breed: "Siamese" | "Persian" | "Maine Coon" | "Ragdoll" | "Bengal" })[]; rain: "cats" | "dogs" })[]

  export type ContractListType = {
elasticsearchSearchExampleGet: ContractType<elasticsearchSearchExampleGetArgument, elasticsearchSearchExampleGetReturns>
elasticsearchSearchExamplePost: ContractType<elasticsearchSearchExamplePostArgument, elasticsearchSearchExamplePostReturns>
elasticsearchSearchExamplePut: ContractType<elasticsearchSearchExamplePutArgument, elasticsearchSearchExamplePutReturns>
elasticsearchSearchExamplePatch: ContractType<elasticsearchSearchExamplePatchArgument, elasticsearchSearchExamplePatchReturns>
elasticsearchSearchExampleDelete: ContractType<elasticsearchSearchExampleDeleteArgument, elasticsearchSearchExampleDeleteReturns>
}

  export const contracts: ContractListType = {
elasticsearchSearchExampleGet: {
          name: "elasticsearchSearchExample",
          authentication: false,
          type: "get",
          handle: (input, auth) => elastic.get("test-1594205156705", auth, input && input.id, input && input.search),
          arguments: {"search":["string","?"],"id":[{"$string":{"regex":"[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}"}},{"$array":{"$string":{"regex":"[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}"}}},"?"]} ,
          returns: {"$array":{"id":{"$string":{"regex":"[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}"}},"name":"string","ownerId":"string","dogs":{"$array":{"name":"string","color":"string","age":"number","breed":{"$enum":["Labrador Retriever","German Shepherd Dog","Golden Retriever","French Bulldog","Bulldog"]}}},"cats":{"$array":{"name":"string","color":"string","age":"number","breed":{"$enum":["Siamese","Persian","Maine Coon","Ragdoll","Bengal"]}}},"rain":{"$enum":["cats","dogs"]}}}},
elasticsearchSearchExamplePost: {
          name: "elasticsearchSearchExample",
          authentication: false,
          type: "post",
          handle: (input, auth) => elastic.post("test-1594205156705", auth, input),
          arguments: {"id":[{"$string":{"regex":"[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}"}},"?"],"name":"string","ownerId":"string","dogs":{"$array":{"name":"string","color":"string","age":"number","breed":{"$enum":["Labrador Retriever","German Shepherd Dog","Golden Retriever","French Bulldog","Bulldog"]}}},"cats":{"$array":{"name":"string","color":"string","age":"number","breed":{"$enum":["Siamese","Persian","Maine Coon","Ragdoll","Bengal"]}}},"rain":{"$enum":["cats","dogs"]}} ,
          returns: {"id":{"$string":{"regex":"[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}"}},"name":"string","ownerId":"string","dogs":{"$array":{"name":"string","color":"string","age":"number","breed":{"$enum":["Labrador Retriever","German Shepherd Dog","Golden Retriever","French Bulldog","Bulldog"]}}},"cats":{"$array":{"name":"string","color":"string","age":"number","breed":{"$enum":["Siamese","Persian","Maine Coon","Ragdoll","Bengal"]}}},"rain":{"$enum":["cats","dogs"]}}},
elasticsearchSearchExamplePut: {
          name: "elasticsearchSearchExample",
          authentication: false,
          type: "put",
          handle: (input, auth) => elastic.patch("test-1594205156705", auth, input, input.id),
          arguments: {"id":{"$string":{"regex":"[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}"}},"name":"string","ownerId":"string","dogs":{"$array":{"name":"string","color":"string","age":"number","breed":{"$enum":["Labrador Retriever","German Shepherd Dog","Golden Retriever","French Bulldog","Bulldog"]}}},"cats":{"$array":{"name":"string","color":"string","age":"number","breed":{"$enum":["Siamese","Persian","Maine Coon","Ragdoll","Bengal"]}}},"rain":{"$enum":["cats","dogs"]}} ,
          returns: {"id":{"$string":{"regex":"[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}"}},"name":"string","ownerId":"string","dogs":{"$array":{"name":"string","color":"string","age":"number","breed":{"$enum":["Labrador Retriever","German Shepherd Dog","Golden Retriever","French Bulldog","Bulldog"]}}},"cats":{"$array":{"name":"string","color":"string","age":"number","breed":{"$enum":["Siamese","Persian","Maine Coon","Ragdoll","Bengal"]}}},"rain":{"$enum":["cats","dogs"]}}},
elasticsearchSearchExamplePatch: {
          name: "elasticsearchSearchExample",
          authentication: false,
          type: "patch",
          handle: (input, auth) => elastic.patch("test-1594205156705", auth, input, input.id),
          arguments: {"id":{"$string":{"regex":"[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}"}},"name":["string","?"],"ownerId":["string","?"],"dogs":[{"$array":{"name":"string","color":"string","age":"number","breed":{"$enum":["Labrador Retriever","German Shepherd Dog","Golden Retriever","French Bulldog","Bulldog"]}}},"?"],"cats":[{"$array":{"name":"string","color":"string","age":"number","breed":{"$enum":["Siamese","Persian","Maine Coon","Ragdoll","Bengal"]}}},"?"],"rain":[{"$enum":["cats","dogs"]},"?"]} ,
          returns: {"id":{"$string":{"regex":"[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}"}},"name":"string","ownerId":"string","dogs":{"$array":{"name":"string","color":"string","age":"number","breed":{"$enum":["Labrador Retriever","German Shepherd Dog","Golden Retriever","French Bulldog","Bulldog"]}}},"cats":{"$array":{"name":"string","color":"string","age":"number","breed":{"$enum":["Siamese","Persian","Maine Coon","Ragdoll","Bengal"]}}},"rain":{"$enum":["cats","dogs"]}}},
elasticsearchSearchExampleDelete: {
          name: "elasticsearchSearchExample",
          authentication: false,
          type: "delete",
          handle: (input, auth) => elastic.del("test-1594205156705", auth, input.id),
          arguments: {"id":[{"$string":{"regex":"[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}"}},{"$array":{"$string":{"regex":"[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}"}}}]} ,
          returns: {"$array":{"id":{"$string":{"regex":"[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}"}},"name":"string","ownerId":"string","dogs":{"$array":{"name":"string","color":"string","age":"number","breed":{"$enum":["Labrador Retriever","German Shepherd Dog","Golden Retriever","French Bulldog","Bulldog"]}}},"cats":{"$array":{"name":"string","color":"string","age":"number","breed":{"$enum":["Siamese","Persian","Maine Coon","Ragdoll","Bengal"]}}},"rain":{"$enum":["cats","dogs"]}}}}
}
